export default (function () {
    /* 通用正则表达式 */
    const reg = {
        description: /^.{0,60}$/,
        longDescription: /^.{0,120}$/,
        IDCardOne: /^[1-9]\d{7}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}$/,
        IDCardTwo: /^[1-9]\d{5}[1-9]\d{3}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}([0-9]|X)$/i,
        bankAccount: /^\d{16,30}$/,
        taxNumber: /^[\da-zA-Z]{15,20}$/,
        address: /^.{0,60}$/,
        cellphone: /^1\d{10}$/,
        telephone: /^\d{3,4}-\d{7,9}(-\d{3,4})?$/,
        fax: /^\d{3,4}-?\d{7,9}$/,
        email: /^[\da-zA-Z_\.\-]+@([-\dA-Za-z]+\.)+[a-zA-Z]{2,}$/,
        YmdDate: /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/,
        YmdMonth: /^[0-9]{4}-[0-9]{2}$/,
        year: /^[1-9]{1}\d{3}$/,
        month: /^([1-9]|1[0-2])$/,
        day: /^([1-9]|[1|2][0-9]|3[0|1])$/,
        zipcode: /^\d{6}$/,
        decimal: /^\d+(\.\d{1,2})?$/,
        vendorName: /^.{1,50}$/,
        vendorAlias: /^.{1,15}$/,
        humanName: /^[\u4E00-\u9FA5a-zA-Z]{1,8}([\s|·][\u4E00-\u9FA5a-zA-Z]{1,8}){0,3}$/,
        username: /^\d*[a-zA-Z_]+\d*$/,
        password: /(?!^(\d+|[a-z]+|[A-Z]+|[~!@#$%\-^&*?]+)$)^[\w~!@#$%\-\^&*?]+$/,
        isNumber: /^\d+$/,
        isEnAndNumber: /^[a-zA-Z\d\.]*$/,
        EnAndNumberLine: /^[a-zA-Z0-9_-]*$/,
        enAndNumberNoDot: /^[a-zA-Z\d]*$/,
        CHAndEN: /^[\u4E00-\u9FA5a-zA-Z]*$/,
        CHAndENAndNum: /^[\u4E00-\u9FA5a-zA-Z0-9_-]*$/,
        CHAndENAndNumNotLine: /^[\u4E00-\u9FA5a-zA-Z0-9]*$/,
        CH: /^[\u4E00-\u9FA5]*$/,
        positiveNumber: /^[1-9]\d*$/,
        twoDotDigits: /^\d+\.?\d{0,2}$/,
        threeDotDigits: /^\d+\.?\d{0,3}$/,
        startWithDigit: /^[1-9]{1}/,
        WideChar: /[\uFF00-\uFFFF]/,
        exSemicolon: /[^;；]/,
        isNumberAndColon: /^[\d|:]+$/,
        appVersion: /^([0]|([1-9][0-9]{0,2}))\.([0]|([1-9][0-9]{0,2}))\.([0]|([1-9][0-9]{0,2}))$/
    };
    const msg = {
        description: '最多60个字符',
        longDescription: '最多120个字符',
        IDCardOne: '请输入15位一代身份证号码',
        IDCardTwo: '请输入18位二代身份证号码',
        bankAccount: '16-30位数字',
        taxNumber: '15-20位数字、大小写字母',
        address: '最多60个字符',
        cellphone: '手机号码格式有误。示例：13811112222',
        telephone: '固定电话格式有误。示例：0571-88888888, 010-88888888-888',
        fax: '传真格式有误。示例：0571-88888888',
        email: '示例：mail@example.com',
        YmdDate: '日期格式有误。示例： 2014-08-08',
        YmdMonth: '格式有误。示例： 2014-08',
        year: '年份格式有误。示例：2014',
        month: '月份格式有误。示例：8, 12',
        day: '日格式有误。示例：3, 25',
        zipcode: '邮政编码为6位数字。示例：310000',
        decimal: '请填写正确数字，最多保留两位小数',
        vendorName: '全称最多50个字符',
        vendorAlias: '别名最多15个字符',
        humanName: '姓名示例：某某，John Smith，某某·某某某',
        username: '用户名由数字，字母或下划线组成，不能全为数字',
        password: '至少包含2种（含）以上，大写字母、小写字母、数字、特殊字符。',
        isNumber: '必须为数字',
        isEnAndNumber: '必须为字母、数字或小数点',
        enAndNumberNoDot: '必须为字母和数字',
        EnAndNumberLine: '必须为字母、数字、下划线或短横线',
        CHAndEN: '请输入中文或英文字母，不支持特殊字符',
        CH: '请输入中文字符',
        CHAndENAndNum: '请输入中英文数字、下划线或短横线',
        CHAndENAndNumNotLine: '请输入中、英文或数字，不支持特殊字符',
        positiveNumber: '请输入正整数',
        twoDotDigits: '请输入数字，最多输入两位小数',
        threeDotDigits: '请输入数字, 最多三位小数',
        startWithDigit: '必须以1-9开头',
        WideChar: '全角字符',
        exSemicolon: '请不要输入；',
        isNumberAndColon: '必须为数字或者：',
        appVersion: '版本号格式不正确'
    };
    return {
        reg,
        msg
    };
})();
